### ISSUE TITLE
Where's the 7711 / Bible stuff?

### ISSUE THREAD

**Issue by RomanADavis** [dougs-repos/Memory#1]

**Comment by dougs-repos** [comment]
I took the folder down because it wasn't quite ready for publication yet. What are you interested in? Maybe what I have will be good enough for you. Are you on The Art of Memory forum?

**Comment by RomanADavis** [comment]
I was interested in trying to develop a way to programmatically generate mnemonics for the bible to help my bible study, in the same vein as RTK / WaniKani for Japanese

**Comment by dougs-repos** [comment]
Roman,

Generating mnemonics by machine goes against the principles of mnemonics
for making them personal and therefore more memorable. Mine are very
imaginative and would require a major AI system to generate. If you want to
make your Bible study easier with better mnemonics, I am willing to help
out where I can. But the Bible requires a very large framework and a focus
on what you want to learn. I backed off learning the individual scriptures
until I got the themes of the chapters down.

I don't know the RTK/Watikani. Do you have an account on the Art of Memory?
Maybe you could find some help there.

Good luck to you and God bless you!


*Sincerely,Doug Hoff*

website <http://doughoff.com/> / Twitter <http://twitter.com/dhkc> /
LinkedIn <http://www.linkedin.com/in/doughoff>

**Comment by RomanADavis** [comment]
Wani Kani is a site that helps people remember Kanji with a combination of spaced repitition and mnemonics for individual kanji (to more easily map appearance to meaning, appearance and meaning to pronunciation, and character combinations to words with meaning and pronunciation), with Wani Kani, the mnemonics themselves are not especially automated, but it definitely had it's place.

One of the biggest things that Wani Kani proved for me was that mnemonics didn't have to be especially personal, as the original mnemonics were just the ones that seemed reasonable to the guy who wrote RTK (James Heisig), but if those don't work for you, you could always use Koohi which crowdsources mnemonics for kanji. If for some reason one of those don't work, in the context of an anki deck or an editable website, you can just write your own. But I hope you can see how already having a deck with memorable stories might save you time so you could focus on making good mnemonics for the ones that were hardest to remember.

So, it did occur to me to try to add some sort of structure to trying to memorize the Bible. One of the more obvious ways to employ automation would be something like, scraping a websites like [this](https://biblehub.com/summary/genesis/) for book summaries. Scraping a site like [this](https://biblesummary.info/genesis) for chapter summaries, then parsing them into an anki deck. The book summaries are a little long for anki decks, but their well structured; they may still serve some use in anki deck split up into paragraphs or something like that. The verse summaries are very short, each 140 characters or less. They should be fine as anki cards themselves; while it may be possible to automate some sort of mnemonic or programmatically generate a memory palace from them, that's likely overkill. 

It's probably more useful to use the new memories as scaffolding for some sort to memorize the scripture. The kind of think I immediately think of is, like, mapping every book to a material, and mapping the keywords from summaries onto some sort of concrete object, and putting a [material] [object] on every door to every room / verse in our memory palace for that chapter. (I suspect this to not work that well and to be the sort of thing I have to test and refine, but I think the basic idea makes sense.)

My idea was to generate memory palaces for holding large amounts of information, and to make the palaces themselves memorable. 

Hyper ideally, you could like, type in an address and get the floor plans for your childhood home and the program generates a 3D model out of that, complete with keywords of [thing you’re trying to memorize] mapped to 3D objects in conspicuous places editable to your needs.

Less ideally, you could use an ARG type thing, that uses the path to your work as a sort of memory palaces: the Dairy Queen is now The Lady more valuable that ruby, the ATM is a pearl of great price, etc.

Least ideal, what I’m likely to do as an early step, is to just figure out how to procedurally generate buildings in a way that’s actually memorable, autofill it in with keywords mapped on to stuff scraped from bing image searches, and see how to make the mnemonics more personal / memorable from there.

And, of course, even less ideal than that, see if I could somehow crowdsource good mnemonics for bible stuff, in the same vain as koohi stories. Actually, it’d be kind of surprising if no one had done this for other things people have to memorize, like med school stuff, spelling etc.

**Comment by RomanADavis** [comment]
The bible stuff has since been readded. Yay!
